apiVersion: v1
kind: Service
metadata:
  name: frontier-service
  labels:
    app: frontier-service
spec:
  type: ClusterIP
  selector:
    app: frontier-service
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004